project 'BTCoreTestFramework.xcodeproj'

# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

use_frameworks!

target 'BTCoreTestFramework' do
  pod 'Masonry', '~> 1.0.2'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'FMDB', '~> 2.6.2'
  pod 'AFNetworking', '~> 3.1.0'
end
